# Generated by Django 2.2 on 2021-06-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondeck', '0015_add_search_to_ticket'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='workspace',
        ),
        migrations.AddField(
            model_name='repository',
            name='workspaces',
            field=models.ManyToManyField(to='ondeck.Workspace'),
        ),
    ]
