# Generated by Django 2.2 on 2021-06-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20210614_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='repo_id',
            new_name='bot_id',
        ),
    ]
