# Generated by Django 2.2 on 2021-06-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_auto_20210615_0004'),
        ('integrations', '0004_auto_20210614_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='watchers',
            field=models.ManyToManyField(to='identity.Identity'),
        ),
    ]
