# Generated by Django 2.2 on 2021-06-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondeck', '0015_add_search_to_ticket'),
        ('integrations', '0005_repository_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='workspaces',
            field=models.ManyToManyField(to='ondeck.Workspace'),
        ),
    ]
