# Generated by Django 2.2 on 2021-06-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_bot_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='provider',
            field=models.CharField(choices=[('slack', 'Slack')], max_length=255, null=True),
        ),
    ]
