name: React 2 S3
description: Deploy a react app to AWS S3
inputs:
  working-directory:
    description: working directory
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm ci
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - name: Build
      run: npm run build
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - name: Upload to S3
      run: ${{ github.action_path }}/deploy_to_s3 "${{ inputs.working-directory }}/build"
      shell: bash
