#!/bin/bash

set -xe

BUILD_FOLDER="${1:-build}"
BUCKET_NAME=$AWS_S3_BUCKET_NAME

GIT_COMMIT="$(git rev-parse --short HEAD)"

echo "$GIT_COMMIT" >> $BUILD_FOLDER/version.txt

DIST="s3://$BUCKET_NAME/builds/$GIT_COMMIT"
echo "Upload destination: $DIST"

if aws s3 sync $BUILD_FOLDER/ "$DIST" --acl="public-read"; then
    cat $BUILD_FOLDER/version.txt
    cat $BUILD_FOLDER/asset-manifest.json
else
    echo "failed to upload build on $DIST"
    exit 1
fi
