# Generated by Django 2.2.10 on 2020-02-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ondeck', '0002_auto_20200225_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='order',
            new_name='position',
        ),
    ]
