# Generated by Django 2.2.11 on 2020-04-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondeck', '0007_auto_20200409_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
