# Generated by Django 2.2.15 on 2020-08-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondeck', '0011_auto_20200420_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('slug', 'workspace')},
        ),
    ]
