# Generated by Django 2.2.6 on 2019-10-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondeck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
