# Generated by Django 2.2.11 on 2020-04-09 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ondeck', '0006_auto_20200409_0336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='uniqueness',
            new_name='value',
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('ticket', 'value')},
        ),
    ]
