name: React
on:
  push:
    paths-ignore:
      - 'backend/**'
      - '.github/workflows/backend*'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./frontend
      GIT_SHORT_SHA: $(git rev-parse --short "$GITHUB_SHA")
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_S3_BUCKET_NAME: ${{secrets.AWS_S3_BUCKET_NAME}}
      RAILWAY_PROJECT_ID: ${{secrets.RAILWAY_PROJECT_ID}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15'
      - run: echo "GIT_SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-6`" >> $GITHUB_ENV
      - run: echo "PUBLIC_URL=https://${{secrets.AWS_S3_BUCKET_NAME}}.s3.awsamazon.com/${{ env.GIT_SHORT_SHA }}" >> $GITHUB_ENV
      - uses: ./.github/actions/deploy-react-to-aws
        with:
          working-directory: ${{ env.working-directory }}
      - run: npm install @railway/cli@0.2.35 -g
      - run: npx railway --version
      - run: INSTALL_DIR="." sh -c "$(curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh)"
      - run: ./railway link ${{env.RAILWAY_PROJECT_ID}}
      - run: ./railway variables set COMMIT=${{ env.GIT_SHORT_SHA }}
