name: React
on:
  push:
    paths-ignore:
      - 'backend/**'
      - '.github/workflows/backend*'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./frontend
      GIT_SHORT_SHA: $(git rev-parse --short "$GITHUB_SHA")
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_S3_BUCKET_NAME: ${{secrets.AWS_S3_BUCKET_NAME}}
    steps:
      - run: echo 'PUBLIC_URL=https://${{secrets.AWS_S3_BUCKET_NAME}}.s3.awsamazon.com/'$(git rev-parse --short HEAD) >> $GITHUB_ENV
      - run: echo ${{ env.PUBLIC_URL }}
