name: React
on:
  push:
    paths-ignore:
      - 'backend/**'
      - '.github/workflows/backend*'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./frontend
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_S3_BUCKET_NAME: ${{secrets.AWS_S3_BUCKET_NAME}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15'
      - uses: ./.github/actions/deploy-react-to-aws
        with:
          working-directory: ${{ env.working-directory }}
