name: Railway
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '15'
      - run: npm install @railway/cli@0.2.35 -g
      - run: npx railway variables set HELLO="world"
